UnitTest/DropCollectionTest.cs, UnitTest/UnitTest.csproj
Here's a trivial DropCollection unit test, if you want it!
=> Added DropCollection unit test.

README.md
=> Chaged (less then 200kb)  to (less than 200kb)  :)

LiteDB/Storage/Services/DiskService.cs
change _writer from BinaryWriter to Lazy<BinaryWriter>
=> _writer => Lazy<BinaryWriter>

LiteDB/Storage/Services/DiskService.cs
=> Revert "_writer => Lazy<BinaryWriter>"

LiteDB/Utils/LiteException.cs, README.md
A few simple grammar/language fixes for the readme. I've made some similar updates to the wiki
=> Readme fixes

LiteDB.Tests/Index/LinqTest.cs, LiteDB/LiteDB.csproj, LiteDB/Query/Impl/QueryEmpty.cs, LiteDB/Query/Linq/QueryVisitor.cs, LiteDB/Serializer/Mapper/Reflection.cs
Implemented feature request in issue #112.
=> Implemented querying collections with Enumerable.All and Enumerable.Any

LiteDB/Document/BsonValue.cs
Specifically for queries involving doubles. Not sure whats up with the newline thing (I'm using githubs interface), but I'm too lazy to fix it.
=> Fixed queries returning incorrect results.

LiteDB.Platform/LiteDB.Tests.Android/TestPlatform.cs, LiteDB.Platform/LiteDB.Tests.iOS/TestPlatform.cs
sorry about the spacings, its Xamarin Studio, never use it that much
=> fix: tests, use temp-path in mobile tests

LiteDB/Storage/Services/RecoveryService.cs
This corrects the following problem :
When Journal is not enabled, TryRecovery() still attempts to access the journal file. If the journal file does not exist, this throws a FileNotFound exception which shows up in the debug output.
=> Added check if Journal is enabled

LiteDB/DbEngine/Disks/EncryptedDiskService.cs, LiteDB/DbEngine/Disks/FileDiskService.cs
=> Logic for checking password moved to the FileDiskService base class

LiteDB/DbEngine/DbEngine/Dump.cs
=> DiskDump now starts a transaction

LiteDB.Shell/Commands/Open.cs, LiteDB.Tests/Tests/TempFile.cs, LiteDB/Utils/ConnectionString.cs
Well all the tests passed on my machine, so I am creating this request again.
Addressing #260
=> ConnectionString class now uses regex to manipulate string

LiteDB.Shell/Commands/Collections/BaseCollection.cs, LiteDB/Engine/Pages/CollectionPage.cs, LiteDB/Engine/Structures/CollectionIndex.cs, LiteDB/Mapper/BsonMapper.cs, LiteDB/Storage/LiteFileInfo.cs, LiteDB/Upgrade/V6/Structures/CollectionIndex.cs, LiteDB/Utils/Extensions/ExpressionExtensions.cs
Regexes that are used repeatedly gained the Compiled flag, to improve their execution speed.
=> Compiled Regex

LiteDB/Engine/LiteEngine.cs
=> Fixed a problem with not closing the file handle before throwing an exception

.travis.yml, .travis/before-install-linux.sh, .travis/before-install-osx.sh
Now we also build for osx: https://travis-ci.org/xied75/LiteDB/builds/210166590
:)
=> add osx for Travis build

LiteDB/Utils/AesEncryption.cs
Also cleaned up disposal of types that may or may not be IDisposable between different framework versions.
Braces are used to limit scope so that disposed instances go out of scope as they do with using{} blocks.
=> Use a cryptographically secure RNG even on .NET standard.

LiteDB/Mapper/BsonMapper.cs
https://github.com/mbdavid/LiteDB/issues/783
=> use mapper serialize method for DbRef id

LiteDB/Repository/LiteRepository.cs
I just added the return value (the document ID) as written in the method's comment.
=> Fixed return value of LiteRepository.Insert method.

LiteDB/Database/Collections/Insert.cs, LiteDB/Engine/Engine/Insert.cs, LiteDB/Engine/LiteEngine.cs
=> A new UpsertBulk method added to solve the problem with high memory usage of Upsert

index.html
=> Fixed typo in website

LiteDB/Client/Mapper/Reflection/Reflection.cs, LiteDB/Document/BsonArray.cs, LiteDB/Engine/Disk/DiskService.cs, LiteDB/Engine/Engine/Delete.cs, LiteDB/Engine/SystemCollections/SysDump.cs, LiteDB/Utils/Extensions/BufferExtensions.cs, LiteDB/Utils/Extensions/LinqExtensions.cs, LiteDB/Utils/Extensions/TypeInfoExtensions.cs, LiteDB/Utils/FileHelper.cs, LiteDB/Utils/Tokenizer.cs
=> Add AddRange<TCollection>(TCollection collection) To BsonArray

LiteDB/Engine/Disk/Serializer/BufferPool.cs, LiteDB/Utils/Pool/ArrayPool.cs, LiteDB/Utils/Pool/BucketHelper.cs
=> Add ArrayPool

LiteDB.Tests/Engine/Transactions_Tests.cs
3 of the 4 transaction unit tests were relying on task.delay which lead to inconsistent successes and failures of those tests. This PR should resolve this by using semaphores to decide when a certain thread may continue.
=> Remove time factor from transaction unit tests

LiteDB/LiteDB.csproj
=> Removed unnecessary packagereferences

LiteDB/Utils/MimeTypeConverter.cs
This adds support for the [WebP image format](https://en.wikipedia.org/wiki/WebP).
=> Add WebP Mime Type to MimeTypeConverter

LiteDB/Engine/Query/IndexQuery/Index.cs
=> Scan method comment fix.

LiteDB.Tests/Mapper/Mapper_Tests.cs, LiteDB/Client/Mapper/BsonMapper.Serialize.cs
=> Fix NullReferenceException in BsonMapper.ToDocument<T>()

LiteDB.Tests/Mapper/GenericMap_Tests.cs, LiteDB/Client/Mapper/BsonMapper.Deserialize.cs, LiteDB/Client/Mapper/Reflection/Reflection.cs
=> Add ISet<T> support to BsonMapper

LiteDB.Tests/Expressions/Expressions_Exec_Tests.cs
Created more tests for SORT function
=> More tests for SORT function

LiteDB.Tests/Internals/Pragma_Tests.cs, LiteDB.Tests/Internals/Sort_Tests.cs, LiteDB/Engine/Engine/Rebuild.cs, LiteDB/Engine/EnginePragmas.cs, LiteDB/Engine/FileReader/FileReaderV7.cs, LiteDB/Engine/FileReader/FileReaderV8.cs, LiteDB/Engine/Pages/HeaderPage.cs, LiteDB/Engine/Services/TransactionService.cs, LiteDB/Engine/Structures/Pragma.cs, LiteDB/Engine/SystemCollections/SysDatabase.cs, LiteDB/Engine/SystemCollections/SysPragmas.cs
Implemented validation functionality for pragmas and added tests
=> Pragma validation and tests

LiteDB.Benchmarks/Benchmarks/Constants.cs, LiteDB.Benchmarks/Benchmarks/Generator/FileMetaDataGenerationDatabaseBenchmark.cs, LiteDB.Benchmarks/LiteDB.Benchmarks.csproj, LiteDB.Benchmarks/Models/FileMetaBase.cs, LiteDB.Benchmarks/Models/FileMetaWithExclusion.cs, LiteDB.Benchmarks/Models/Generators/FileMetaGenerator.cs, LiteDB.Benchmarks/Program.cs, LiteDB.sln
This is just the initial setup for the benchmarking project and includes currently only benchmarks for my testdata generator.
More benchmarks are currently being worked on, but it will take a bit more time.
=> Initial setup for benchmark project

LiteDB.Shell/Commands/Version.cs, LiteDB.Shell/Shell/Env.cs, LiteDB.Tests/Database/IndexSortAndFilter_Tests.cs, LiteDB.Tests/Engine/Rebuild_Tests.cs, LiteDB.Tests/Query/GroupBy_Tests.cs, LiteDB.Tests/Query/Person_Tests.cs, LiteDB/Client/Database/Collections/Include.cs, LiteDB/Client/Database/ILiteCollection.cs, LiteDB/Client/Database/ILiteDatabase.cs, LiteDB/Client/Database/ILiteRepository.cs, LiteDB/Client/Database/LiteCollection.cs, LiteDB/Client/Database/LiteDatabase.cs, LiteDB/Client/Database/LiteRepository.cs, LiteDB/Client/Storage/ILiteStorage.cs, LiteDB/Client/Storage/LiteFileInfo.cs, LiteDB/Client/Storage/LiteFileStream.cs, LiteDB/Client/Storage/LiteStorage.cs
fixes #678
related to https://github.com/mbdavid/LiteDB/pull/1310 (see last comments)
Hi,
I just want to be able to mock those classes in my code even if I keep a reference on your library.
Thanks
=> Add interfaces to LiteDatabase, LiteCollection, LiteRepository

LiteDB/Engine/Query/IndexQuery/IndexIn.cs
=> Bug fix in IndexIn

LiteDB/Client/SqlParser/Commands/Update.cs, LiteDB/Client/SqlParser/SqlParser.cs
=> Fix ParseUpdate name

LiteDB.Tests/Database/Update_V5_Tests.cs, LiteDB.Tests/Engine/Update_V5_Tests.cs, LiteDB/Engine/Query/QueryExecutor.cs, LiteDB/LiteDB.csproj
=> Fix cursors not being closed after update

LiteDB/Engine/Services/TransactionService.cs
This fixes the order of writes and adds appropriate flushes when committing to disk.
This ensures that the journal is written to disk before proceeding with any changes and avoids leaving the database in an inconsistent state in case of a power failure.
=> Fix corrupt database when saving is interrupted

.travis.yml
This PR aims to resolve build config warnings/deprecations in the Travis CI config file.
=> [WIP] Fix TravisCI build config warnings

LiteDB.Tests/Internals/Disk_Tests.cs, LiteDB/Engine/Disk/DiskWriterQueue.cs
https://github.com/mbdavid/LiteDB/issues/1490
=> Use thread pool in DiskWriterQueue

LiteDB.Tests/Mapper/LinqBsonExpression_Tests.cs, LiteDB/Client/Mapper/Linq/TypeResolver/EnumerableResolver.cs
=> Added linq to BsonExpression conversion for Any()

LiteDB.Tests/Expressions/Expressions_Exec_Tests.cs, LiteDB/Document/Expression/Parser/BsonExpressionOperators.cs
Add tests for each fixed case, they all used to fail.
=> Fix several "copy/paste" errors in "ALL" operators.

LiteDB/Client/Database/LiteQueryable.cs
=> Fix LiteQueryable.Count() overwriting query

LiteDB/Client/Database/LiteQueryable.cs
=> Added try-finally blocks to LiteQueryable.Count/LongCount/Exists

LiteDB/Client/Database/LiteDatabase.cs, LiteDB/Client/Structures/ConnectionString.cs, LiteDB/Client/Structures/UpgradeOption.cs, LiteDB/Engine/Engine/Rebuild.cs, LiteDB/Engine/Engine/Upgrade.cs
=> Created option for data-only upgrade

LiteDB.Tests/Document/Json_Tests.cs, LiteDB/Document/Json/JsonWriter.cs
=> Improved json serialization in strings

LiteDB.Tests/Mapper/LinqBsonExpression_Tests.cs, LiteDB/Client/Mapper/Linq/LinqExpressionVisitor.cs
=> Fix Linq expressions parsing on Enum when EnumAsInteger=false

LiteDB/Client/Shared/SharedEngine.cs
=> Fix mutex not being released after EnsureIndex in shared mode

LiteDB.Tests/Database/Document_Size_Tests.cs, LiteDB.Tests/Issue1585.cs, LiteDB/Client/SqlParser/Commands/Create.cs, LiteDB/Client/SqlParser/Commands/Delete.cs, LiteDB/Client/SqlParser/Commands/ParseLists.cs, LiteDB/Client/SqlParser/Commands/Select.cs, LiteDB/Client/SqlParser/Commands/Update.cs, LiteDB/Document/Expression/BsonExpression.cs, LiteDB/Document/Expression/Parser/BsonExpressionFunctions.cs, LiteDB/Document/Expression/Parser/BsonExpressionOperators.cs, LiteDB/Document/Expression/Parser/BsonExpressionParser.cs, LiteDB/Engine/Engine/Delete.cs, LiteDB/Engine/Query/QueryOptimization.cs, LiteDB/Engine/Query/Structures/IndexCost.cs
=> Rework in the parameters system of a BsonExpression

LiteDB/Client/Mapper/BsonMapper.Serialize.cs, LiteDB/Client/Mapper/BsonMapper.cs
The limit of 20 may not me enough for some situations
=> Make MAX_DEPTH a variable property

LiteDB.Tests/Database/AutoId_Tests.cs, LiteDB.Tests/Database/DbRef_Include_Tests.cs, LiteDB.Tests/Database/DbRef_Index_Tests.cs, LiteDB.Tests/Mapper/StructField_Tests.cs, LiteDB/Client/Database/LiteDatabase.cs, LiteDB/Client/Database/LiteRepository.cs, LiteDB/Engine/EngineSettings.cs
Hi 
PR has been created for suggestion #1692. 
I’ve introduced new parameter to existing cotr and altered existing xunit tests. I’ve try to came up with new unit test idea that would test read/write scenario for LogStream, but it already exists in Disk_Tests.Disk_Read_Write()
Cheers
Piotr
=> Introducing new ctor paramter for LiteDatabase

LiteDB.Tests/Issues/Issue1860_Tests.cs, LiteDB/Client/Mapper/BsonMapper.cs
fix issue about enums in constructor #1860
=> fix constructor with enum parameter crashes

LiteDB/Engine/Engine/Transaction.cs
If you prefer to use manual transactions then you won't ever have soft checkpoint. This PR fixes this issue and also removes checkpoint logic from nested transactions which always guaranteed to be locked by outer transaction, so just adds overhead.
=> Fixed: Pragma checkpoint ignored for manual transactions (BeginTrans/Commit)

LiteDB.Tests/Issues/Issue1651_Tests.cs, LiteDB.Tests/Issues/Issue1865.cs, LiteDB.Tests/Issues/Issue1865_Tests.cs, LiteDB/Client/Mapper/BsonMapper.cs
=> fix #1865 Wrong type after include directive

LiteDB.Tests/Document/Case_Insensitive_Tests.cs, LiteDB/Document/BsonArray.cs, LiteDB/Document/BsonDocument.cs, LiteDB/Document/BsonValue.cs
=> BsonDocument compare with collation

LiteDB/Client/Mapper/BsonMapper.Deserialize.cs
Fix the ambigous match found when deserialize list
=> Ambigous match found

README.md
LiteDB.FSharp does not currently work with v5.
=> Clarify LiteDB.FSharp version support

LiteDB/Engine/Engine/Upgrade.cs, LiteDB/Engine/Pages/HeaderPage.cs, LiteDB/Engine/Services/TransactionMonitor.cs, LiteDB/Engine/Services/TransactionService.cs, LiteDB/Utils/FileHelper.cs
=> Fix all kind of typos

LiteDB/Engine/Services/SnapShot.cs
This fix prevents ENSURE ... Clear() cache error and DB corruption problem, which is described in this issue: https://github.com/mbdavid/LiteDB/issues/2480
=> Prevent using disposed snapshots

README.md
=> Add-Badges

LiteDB.Shell/Shell/InputCommand.cs
when sending the Ctrl+C control code `ETX` to quit the application.
=> Fix crash with stack trace

LiteDB.Benchmarks/LiteDB.Benchmarks.csproj, LiteDB.Benchmarks/Program.cs
Just updating the `BenchmarkDotNet` version
=> [♻️ Housekeeping] Update benchmark project

LiteDB.Tests/Issues/Issue2506_Tests.cs, LiteDB.Tests/LiteDB.Tests.csproj
Oops, looks like I committed directly to the GH-Pages branch without making a pull request.
Nevermind, anyway this pull request adds the related tests for that commit.
Fixes #2506
=> Add tests for Issue #2506 fix
