LiteDB/Query/Impl/QueryContains.cs

To prevent #75, we need to check if the value is actually a string, otherwise we might get a `NullReferenceException`.

Check value before executing Contains - fixes #75

---

LiteDB.Tests/Mapping/MapperTest.cs
LiteDB/Core/Database/Utils.cs
LiteDB/Serializer/Mapper/BsonMapper.Deserialize.cs

Fixed issue when type derived from IEnumerable<>, ICollection<>, or IList<>, etc.. is used deserialization fails.
For details please see issue #92

Added support for deserialization of types derived from IEnumerable<>

---

LiteDB/DbEngine/Disks/FileDiskService.cs

Use `DateTime.UtcNow` for timeout checking, because `DateTime.UtcNow` is much more faster than `DateTime.Now`
`DateTime.Now`: 1071 ms
```C#
for (int i = 0; i < 1000000; i++)
{
var timer = DateTime.Now.Add(TimeSpan.FromMinutes(1));
var tmp = DateTime.Now < timer;
}
```
`DateTime.Now`: 37 ms
```C#
for (int i = 0; i < 1000000; i++)
{
var timer = DateTime.UtcNow.Add(TimeSpan.FromMinutes(1));
var tmp = DateTime.UtcNow < timer;
}
```
`DateTime.Now`: 526ms
```C#
var timer = DateTime.Now.Add(TimeSpan.FromMinutes(1));
for (int i = 0; i < 1000000; i++)
{
var tmp = DateTime.Now < timer;
}
```
`DateTime.UtcNow`: 10ms
```C#
var timer = DateTime.UtcNow.Add(TimeSpan.FromMinutes(1));
for (int i = 0; i < 1000000; i++)
{
var tmp = DateTime.UtcNow < timer;
}
```
Related [blog …

Use UtcNow in the FileDiskService.TryExec

---

LiteDB/Core/Database/OnModelCreating.cs
LiteDB/Serializer/Mapper/BsonMapper.cs
LiteDB/Serializer/Mapper/Reflection.cs

Using of double checked locking instead of simple lock for the `BsonMapper` cache,  `PropertyMapper` cache and reflection constructor's cache.

Optimize locking

---

LiteDB/DbEngine/Services/CacheService.cs
LiteDB/Serializer/Json/JsonWriter.cs

In the following cases we can replace LINQ.Count() to improve performance.

Replace unnecessary LINQ.Count() usage

---

LiteDB/DbEngine/Disks/FileDiskService.cs

I was a bit frustrated by the constant mscorlib exceptions arising from FileDiskServer::TryRecovery, so I added an if statement to check if the journal function is enabled.
I don't know if you want this fixed, but I find the lack of exceptions from it pleasing.

Fixed mscorlib exception which arises from journalling not being enabled

---

LiteDB.Tests/LiteDB.Tests.csproj
LiteDB.Tests/Tests/ShrinkTest.cs
LiteDB/DbEngine/DbEngine/Shrink.cs

Add Shrink() tests for {0, 1, 2} collections;
Fix Shrink() implementation to re-open the disk service after each implicit transaction from Insert collection.

Issue #249.

---

LiteDB.Tests/Tests/ShrinkTest.cs
LiteDB/Query/Linq/QueryVisitor.cs
LiteDB/Serializer/Mapper/BsonMapper.Deserialize.cs

please note: a few c#6 to c#5 changes come with this.

Better error message on impossible cast

---

LiteDB.Tests/Tests/MapperInterfaceTest.cs
LiteDB/Serializer/Mapper/Reflection.cs

Fixed an issue where multi-threaded calls to Reflection.CreateInstance for the same Type would cause an exception as the same item would be added to the _cacheCtor dictionary more than once. To see this in action simply run the ThreadedMappingShouldNotCauseConstructorException against the original Reflection.cs class. To fix the issue I simply moved the lock up so it wraps around all accesses to _cacheCtor.
It might also be a good idea to include the original Exception as an InnerException in the thrown exception. I found it a bit confusing getting an exception telling me my classes required a Parameter-less constructor when they already had one. If you want I can also add this?

Fixed locking issue in Reflection

---

LiteDB/Utils/IndexNotFoundException.cs
LiteDB/Utils/LiteException.cs

This is just a tiny cosmetic change. In accordance with the [suggestions of MSDN](https://msdn.microsoft.com/en-us/library/seyhszts%28v=vs.110%29.aspx) [1], added punctuation to error messages. Also improved a few messages slightly to make them easier to understand.
[1]
> Use grammatically correct error messages, including ending punctuation. Each sentence in a description string of an exception should end in a period. For example, "The log table has overflowed.” would be an appropriate description string.

Add punctuation in error messages; slightly improve a few message texts

---

LiteDB/Mapper/Reflection/Reflection.cs
LiteDB/Utils/LiteException.cs

In reflection.cs, there is information lost when construction fails. This PR includes the thrown exceptions, if any, as inner exception, to make debugging these situations easier.

include inner exception information (if available) when construction fails

---

LiteDB/DbEngine/Disks/FileDiskService.cs

Reduce locked file wait interval.
This helps a lot in cases with concurrent access. It enormously improved throughput and latency in my tests, and also helped getting a _lot_ fewer timeouts.
Maybe this also helps with #322.

Reduce locked file wait interval

---

LiteDB.Tests/Database/NullRefTests.cs
LiteDB.Tests/LiteDB.Tests.csproj
LiteDB/Mapper/BsonMapper.Deserialize.cs
LiteDB/Mapper/BsonMapper.cs

Hi,
I encountered a NullReferenceException during deserialization. The PR includes a test that reproduces the exact scenario. A quick summary of the steps:
- create and insert an entity that has a list, which is a DbRef
- create an instance of the referenced entity, add it to the first entity and store both
- delete the referenced entity (directly, not by removing it from the list of the first entity)
- load the first entity again => throws
The fix results in ignoring the deleted entity and just returning an empty list.

Fix for NullReferenceException when deserializing a deleted DbRef

---

LiteDB.Shell/Commands/Collections/Bulk.cs
LiteDB.Shell/Commands/Console/ShowCollections.cs
LiteDB.Shell/Shell/Env.cs
LiteDB.Shell/Shell/ShellProgram.cs
LiteDB.Shell/project.json

Some minor tweaks so the shell can be built with dotnet core.
I also fixed a null reference exception when running show collections with no database file opened.
This is only lightly tested with basic CRUD operations. :)

Add dotnet core support for shell

---

LiteDB.Tests/Database/IndexSortAndFilterTest.cs
LiteDB.Tests/LiteDB.Tests.csproj
LiteDB/Engine/Query/QueryAnd.cs

Sort does not work if filter is also used. Following example from Wiki does not work:
`var results = col.Find(Query.And(Query.All("Age", Query.Descending), Query.Between("Age", 20, 30)), limit: 100);
`
This happens because QueryAll is ignored in QueryAnd

bug fix: ignoring QueryAll will cause sort to be ignored

---

.travis.yml
LiteDB.Tests/Concurrency/PerformanceTest.cs
LiteDB.Tests/LiteDB.Tests.dotnet.csproj
LiteDB/LiteDB.dotnet.csproj
README.md

These changes would be enough for now to test netstandard code on Travis, only missing an solution file to enable opening solution on VS 2017, will PR that later if needed.
There are two tests failing: https://travis-ci.org/xied75/LiteDB/builds/209813288
Once you merge, you can login to Travis with your GitHub account then switch on Travis build for your main stream and update the README.md to change my travis to yours.

add Travis CI build files, targetting dotnet 1.1

---

LiteDB/Engine/Engine/Shrink.cs

temp.FileLength will throw NullReferenceException after engine is Disposed, because LiteEngine.Dispose() disposes also DiskService (temp).

Fix NullReferenceException when using FileDiskService during Shrink

---

LiteDB.Tests/Document/DocumentTest.cs
LiteDB/Document/BsonDocument.cs

Finally found some time to add code to copy a BsonDocument to an array.
This fixes #557 
I've also added a test because I'm a TDD guy. Please feel free to throw it away if you think this is over the top... i'm used to it :-)

BsonDocument copies its properties by reference  to KV array

---

LiteDB/Engine/Disks/FileDiskService.cs
LiteDB/Engine/Disks/IDiskService.cs
LiteDB/Engine/Disks/StreamDiskService.cs
LiteDB/Engine/Services/TransactionService.cs

This solves #574 . However only the for the portable version, because Flush(true) API has been added in .NET Framework 4 (and works properly since .NET Framework 4.5). So it will not work in .NET Framework 3.5.

Added flushing OS cache to medium

---

LiteDB.Tests/Database/LockTimeoutTests.cs
LiteDB.Tests/LiteDB.Tests.csproj
LiteDB/Engine/Services/LockService.cs

If LiteDB cannot acquire lock in given timeout an exception is thrown

throw exception if lock cannot be acquired #630

---

LiteDB.Shell/Shell/Display.cs

[Shell] Unescape unicode characters before output

---

LiteDB/Document/BsonDocument.cs

The maximum document size of 1 megabyte is no longer enforced. Creating bson documents larger than 1 megabyte works fine. BsonDocument.MAX_DOCUMENT_SIZE is not referenced by any code. (The 512 byte size limit for indexed fields remains).

Remove unused BsonDocument.MAX_DOCUMENT_SIZE

---

LiteDB.Shell/Properties/AssemblyInfo.cs
LiteDB.Tests/Properties/AssemblyInfo.cs
LiteDB.nuspec
LiteDB/Properties/AssemblyInfo.cs

Alternative fix for #657 
This fix does not alter the build process it just adds a proper reference in nupkg and bumps version.
@mbdavid This is quite important and urgent because net45 version still has no protection against #574 because it uses a wrong DLL.

Alternative fix for #657 (TFM for net45)

---

LiteDB.Tests/Engine/ObjectIdTest.cs
LiteDB/Document/ObjectId.cs

Current implementation of Equals for ObjectId throws NullReferenceException when other is null when it should return false (see https://msdn.microsoft.com/en-us/library/bsc2ak47(v=vs.110).aspx).
Added test to reproduce the issue then fixed the implementation.

ObjectId's Equals should return false when other is null.

---

LiteDB/Mapper/Linq/QueryVisitor.cs

Hi ,  
Actually，it,s not a good idea to use exception for flow control. 
This update can reduce exception throw when use complex linq query.   
When I open  ' break all exception when Common Language Runtime Exceptions happen' in visual studio , it always break when I use complex linq .

reduce exception throw when use complex linq query

---

.editorconfig
LiteDB/Repository/LiteQueryable.cs
LiteDB/Repository/LiteRepository.cs

I added an EditorConfig file in order to set the indentation globally (works on VS2017+ and with ReSharper).
Also I added a LiteRepository constructor which accepts a pre-existent LiteDatabase instance instead of creating a new one (useful in case of an encrypted database or of needing logging for debugging purposes). The new constructor also gives the option to dispose the database's instance together with the repository's. Old constructors have been redirected to the new one for consistency.

Additional constructor in LiteRepository and EditorConfig file

---

LiteDB.Tests/Database/ConnectionString_Tests.cs
LiteDB/Utils/ConnectionString.cs

This an amended version of #883 with suggested property initializer usage and unnecessary LiteDbBuildConfiguration removed.

Fix "new ConnectionString()" not containing default values

---

LiteDB/Engine/Query/QueryIn.cs

The **ToString** method in the **QueryIn** class returns only a collection of types with no values. The remaining **Query** classes return all required values as a string. I use this method for the test, and for QueryIn it's not impossible.
I added output of all values, separated by a comma. Maybe it will be interesting to you.
Sorry for poor english.

Microfix for ToString method within QueryIn class.

---

LiteDB/Utils/Extensions/StreamExtensions.cs

Ran into this issue on OS X, same as #787 and #908 
Unfortunately, .net Core has no way to see if FileStream.Lock is supported, the code [just throws an Exception](https://github.com/dotnet/corefx/blob/cbdc1817946b44b747c481a3782450d8d2a54942/src/Common/src/CoreLib/System/IO/FileStream.OSX.cs).
One option would be to try to open and Lock the file during `FileDiskService.Initialize`, and change to Exclusive if it throws, but that would be a bigger functional change than just catching and showing the message.

If FileStream.Lock is not supported, point towards the solution

---

LiteDB.Shell/Shell/ShellException.cs

Addresses warning CA2237: https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2237-mark-iserializable-types-with-serializableattribute

Mark class [Serializable] to address warning

---

LiteDB/Storage/LiteFileInfo.cs

This allows better support for using the the path as the id. Otherwise, if an id has a space an InvalidFormat exception will be thrown.

Support FileStorage ids with spaces 

---

LiteDB/Storage/LiteFileStream.cs

Fixes https://github.com/mbdavid/LiteDB/issues/742
According to MS [documentation](https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-1.1/b1yfkh5e(v%3dvs.71)) any managed calls can't be called from the finalizer

Improve Dispose pattern implementation

---

README.md

Just noticed that there were mixed tabs and spaces in the README sample code, causing it to misalign. Several of the blank lines also started with tabs, so I cleaned them up as well.

Fix mixed leading whitespace in sample code

---

LiteDB.Studio/ICSharpCode.TextEditor/Resources/SQL-Mode.xshd
LiteDB/Document/Expression/Methods/Misc.cs
LiteDB/Document/Expression/Parser/BsonExpressionParser.cs

- `TOP(enumerable, n)`: returns the first `n` elements of `enumerable`
- Silent conversions from enumerable to array were added where appropriate

TOP function and silent conversion from enumerable to array

---

LiteDB/Client/Shared/SharedDataReader.cs
LiteDB/Client/Shared/SharedEngine.cs
LiteDB/Client/Storage/LiteFileStream.cs
LiteDB/Document/DataReader/BsonDataReader.cs
LiteDB/Engine/LiteEngine.cs
LiteDB/Engine/Structures/PageBuffer.cs

Remove unnecessary finalizers which would end up in the finalizer queue, doing unnecessary work.
Objects with finalizers will survive at least one garbage collection and get promoted to a higher generation since the GC has to wait for their finalizers to get executed before reclaiming their memory. This means that they need at least 2 garbage collection before their memory is reclaimed which is especially bad for `PageBuffer` since it maintains a reference to a large `byte[]` object.
I did a simple test on a relatively large dataset (same dataset generated by LiteDB.Demo, that is, 1 million documents) and ran `col.FindAll().Count()` on it. It registered 29001 `PageBuffer` objects in the finalizer queue which is unnecessary, since `PageBuffer` does not do any meaningful work in its …

Remove unnecessary finalizers

---

LiteDB/Utils/Extensions/BufferExtensions.cs

float* and double* are now cast to uint* and ulong* before being converter to byte[]. This should fix `DataMisalignedException` being throw in some architectures (see #1373).

Changes in BufferExtensions.ToBytes for float and double

---

LiteDB/LiteDB.csproj

This PR hopefully fixes #1459, but to fully test whether this change fixes it, we need to bump the version (5.0.3?) and release a new NuGet package

Fixed Part URI cannot start with two forward slashes

---

LiteDB/Client/Mapper/BsonMapper.Deserialize.cs
LiteDB/Utils/Extensions/TypeInfoExtensions.cs

I have came across performance drop when reading from DB after upgrade from v3 to v5.
The profiler shows that one of bottlenecks is `IsAnonymousType` method which is quite expensive.
This fix resolves two problems.
1. call `IsAnonymousType` only if `BsonValue.IsDocument`
2. optimise `IsAnonymousType` method - use `Attribute.IsDefined` instead of `GetCustomAttributes`, because it is more performant (there is `#if` because it is not available for .NET Standard 1.3)

Optimize performance of IsAnonymousType method.

---

LiteDB.Tests/Mapper/Dictionary_Tests.cs
LiteDB/Client/Mapper/BsonMapper.Deserialize.cs

Problem: BsonMapper correctly creates Dictionary and Hashtable instances but the collections are empty.
P.S. Hashtables are important, for example they are used as "native dictionaries" in PowerShell.
The original line `if (o is IDictionary && typeInfo.IsGenericType)` has two problems:
- it excludes non-generic dictionaries, for example `Hashtable` (quite important type in PowerShell)
- it fails to deserialize `object` as `Dictionary` because it checks `typeInfo` obtained for `object` (non-generic of course)

Fix Deserialize Object (as Dictionary) and Hashtable.

---

LiteDB/Document/Expression/BsonExpression.cs

- It is de-facto sealed because it provides no public or protected constructors.
- Avoid questions like #1468 and unsuccessful attempts to derive from BsonExpression.

Make BsonExpression explicitly sealed.

---

LiteDB/Client/Database/Collections/Find.cs

Fix limit and offset Query parameters being overriden with default values in Find method call

---

LiteDB/Document/BsonValue.cs

See #1529 .
The documentation of the `Enum.CompareTo` (on which `BsonValue.CompareTo` depends) method states that it might return any number greater than zero if `this` is greater than `target`. However, the implementation of the method always returned `1` in this case. Our implementation of `BsonValue.CompareTo` depended on this fact.
The implementation of `Enum.CompareTo` was recently changed in the CoreCLR, which broke `BsonValue.CompareTo`.

Fix BsonValue enum CompareTo for newer CoreCLR versions

---

LiteDB/Engine/Pages/CollectionPage.cs
LiteDB/Engine/Pages/DataPage.cs
LiteDB/Engine/Pages/IndexPage.cs

Between 5.0.2 and 5.0.3 exception was changed on these lines, but "throw" keyword was missed.
It can cause unexpected behavior, if page is parsed with invalid PageType, what is possible in some cases like in https://github.com/mbdavid/LiteDB/issues/1503

Add missed throw keyword

---

LiteDB.Tests/Mapper/Dictionary_Tests.cs
LiteDB/Client/Mapper/BsonMapper.Deserialize.cs
LiteDB/Client/Mapper/BsonMapper.Serialize.cs

It used to fail due to ``Exception calling "Serialize" with "2" argument(s): "Index was outside the bounds of the array."`` because the original code assumed IDictionary is generic and requested invalid ``GetGenericArguments()[1]``.
Also added the test covering the problem case.
Also tweaked my previous fix of deserializing dictionaries, to avoid redundant "expensive" casts.

Fix serialization of non-generic IDictionary, for example Hashtable.

---

LiteDB.Tests/Engine/Index_Tests.cs
LiteDB/Client/Database/Collections/Index.cs

Both overloads of `EnsureIndex` used wrong `string.IsNullOrEmpty` for checking
the expression parameter (probably copy/paste mistake). This triggered the
implicit operator `String` on null expressions and resulted in not clear
NRE exceptions instead of clear `ArgumentNullException`.
Also added a test covering both overloads with null expressions and, for
completeness, with null name.

Fix wrong NRE on passing null expression to EnsureIndex.

---

LiteDB.Tests/Mapper/LinqBsonExpression_Tests.cs
LiteDB/Client/Mapper/Linq/TypeResolver/DateTimeResolver.cs

Added Linq-to-BsonExpression conversion for DateTime.ToUniversalTime()

---

LiteDB.Tests/Engine/Index_Tests.cs
LiteDB/Document/BsonArray.cs

- Tests for multikey index
- `BsonArray(BsonValue[])` changed to `BsonArray(params BsonValue[])`

More tests for multikey index and params BsonArray constructor

---

src/content/docs/Indexes.md

The relative links at the docs are wrong [here](https://www.litedb.org/docs/indexes/)

docs: fix hugo links

---

LiteDB.Tests/Issues/Issue1838_Tests.cs
LiteDB/Document/Expression/Parser/BsonExpressionOperators.cs

As per ```BsonMapper``` ,``` TimeSpan``` is mapped to ```Ticks``` i.e. Int64 .
In Minus and Addition , it was trying to cast long value to double and adding as Days.
Looking at the code , instead of adding/substracting days - Ticks can be used.
Other way around is changing BsonMapper to map Days property instead of Ticks, but this could not be sufficient in some scenarios and Ticks provide standard approach.

fix(1838):ArgumentException thrown when subtracting TimeSpan from DateTimeOffset in query

---

LiteDB/Utils/Constants.cs

When using the nuget package, in debug builds the ensure swallows any error. The "Debug.Fail()" is being optimized away.
This is the code from the latest nuget package:
```
/// <summary>
/// Ensure condition is true, otherwise throw exception (check contract)
/// </summary>
[DebuggerHidden]
public static void ENSURE(bool conditional, string message = null)
{
if (!conditional && !Debugger.IsAttached)
throw new Exception("LiteDB ENSURE: " + message);
}
```
In debug builds, errors are just swallowed without any information.

Throw ENSURE exception also with attached debugger

---

LiteDB.Shell/Commands/Help.cs

When you try to run the shell help command you get the exception Object reference not set to an instance of an object.
The reason is that `CustomAttributeExtensions.GetCustomAttributes` where missing the type where to search
Example:
```Welcome to LiteDB Shell
Getting started with `help`
> help
Object reference not set to an instance of an object.
>
```

Fix NullPointer for shell help command

---

LiteDB.Tests/Engine/Transactions_Tests.cs
LiteDB/Engine/Services/TransactionMonitor.cs

We have problem with our server which eventually became unstable. In log I can see something like:
```
[21:12:18.597] [75] [Error] [Eco] Error inserting stat of type ItemCraftedAction into databaseLiteDB.LiteException: Database lock timeout when entering in transaction mode after 00:01:00
at LiteDB.Engine.LockService.EnterTransaction()
at LiteDB.Engine.TransactionMonitor.GetTransaction(Boolean create, Boolean queryOnly, Boolean& isNew)
at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
at LiteDB.Engine.LiteEngine.Insert(String collection, IEnumerable`1 docs, BsonAutoId autoId)
at LiteDB.LiteCollection`1.Insert(T entity)
at Eco.Stats.Stats.Record(IStat obj)
[21:12:18.597] [146] [Error] [Eco] Error inserting stat of type ItemCraftedAction into databaseLiteDB.LiteException: Database …
```

Fix issue with leaking transaction in TransactionMonitor.GetTransaction

---

LiteDB/Client/Database/LiteDatabase.cs

Fixed typos in LiteDatabase.cs

---

LiteDB/Client/Shared/SharedEngine.cs

Fix for #2292 
local variable _stack was causing multiple threads to get into synchronized area of code. 
Changed the logic to acquire mutex for every DB open call and release on every DB close call to synchronize any operation across threads and processes

use only mutex for Shared engine open and close synchronization and remove locks

---

LiteDB.Tests/Mapper/LinqBsonExpression_Tests.cs
LiteDB/Client/Mapper/Linq/TypeResolver/EnumerableResolver.cs

It looks like there's a typo in EnumerableResolver.ResolveMethod()'s handling for "Min(Func<T,TResult>)" (comparing against the three similar query expressions above).
This fixes it (and slightly improves the tests).

Fix Min(Func<T,TResult>) handling

---

LiteDB/Client/Database/LiteDatabase.cs

"a entity" > "an entity" grammatical typo.

Fixed typo

---

LiteDB.Tests/Internals/Aes_Tests.cs
LiteDB/Engine/Disk/Streams/AesStream.cs

This fix addresses corruption of data/log file which can lead to "Invalid Password" exception [Issue](https://github.com/mbdavid/LiteDB/issues/2343)
Changes:
+ If *bytes[32..63]* is `0`, then write encrypted 1s to *bytes[32..63]*
+ New unit tests to verify:
+ If AesStream can handle a stream of length less than 8192 bytes
+ If AesStream can handle a stream where *bytes[17..8191]* is `0`
+ Removed the logic from AesStream ctor to add padding of 8175 bytes while creating new "hidden" page for encrypted data/log file.

Fix AesStream Invalid Password exception in corrupted files

---

LiteDB/Engine/Services/LockService.cs

Fix for:
#641, #1637, #1993, #2017
resolving issue of 
"ClassName": "System.Threading.SynchronizationLockException",
"Message": "The read lock is being released without being held.",
Issue is that the ReaderWriterLockSlim can be released or not set if not needed and so the code as it stands will attempt to call ExitReadLock() and this will throw an unhandled exception error. 
I've added and If statement check to ensure there is exactly a ReadLock and also put it in a try catch in the event the Read is released within the small fraction of time the exit is called, so the remaining execution of code can run as needed. 
I suspect that this ReleaseTransaction method that is referenced is multiple places is being called, or its just the lock is released too soon, but this fixes that until a …

Update LockService.cs to fix "The read lock is being released without being held" error. Fix for #641, 1637, 1993, 2017

---

LiteDB/Engine/Disk/DiskWriterQueue.cs

Remove if queue empty check that does not reset running flag. If the queue was already emptied out by the previous ExecuteQueue, then this way it will always reset running flag back to 0.

Fix for issue: https://github.com/mbdavid/LiteDB/issues/2307

---

LiteDB/Engine/Sort/SortDisk.cs

One way to fix error sorting large collections in a database with enabled AES encryption.
Now the buffer is written page by page knowing that the container size is always a multiple of the PAGE_SIZE.
This will avoid problems no matter what type of writer is used.

Fix #2300 issue with big collection sort

---

LiteDB/Engine/Disk/Streams/AesStream.cs
LiteDB/Engine/FileReader/FileReaderV7.cs
LiteDB/Utils/LiteException.cs

Added dedicated `FileNotEncrypted` and `InvalidPassword` exceptions with their unique error codes to `LiteException`, replaced invocations in `AesStream` and `FileReaderV7`.
Closes https://github.com/mbdavid/LiteDB/issues/2257

Added unique error codes to encryption-related exceptions

---

LiteDB/Client/Mapper/BsonMapper.cs
LiteDB/Client/Mapper/MemberMapper.cs

support Ignore 
code use like 
```C#
BsonMapper.Global.ResolveMember = (Type type, MemberInfo memberInfo, MemberMapper memberMapper) =>
{
if (type.IsSubclassOf(typeof(EntityBase)))
{
if (memberInfo.GetCustomAttributes<PrimaryKeyAttribute>().Any())
{
memberMapper.FieldName = "_id";
}
if (memberInfo.GetCustomAttributes<AutoIncrementAttribute>().Any())
{
memberMapper.AutoId = true;
}
if (memberInfo.GetCustomAttributes<IgnoreAttribute>().Any())
{
memberMapper.IsIgnore = true;
}
}
};
```

ResolveMember Extension

---

LiteDB/Engine/Disk/DiskService.cs
LiteDB/Engine/Disk/DiskWriterQueue.cs
LiteDB/Utils/AsyncManualResetEvent.cs

It is relatively easy to put the DiskWriterQueue into a state where it does nothing. It is caused by mismatches where the logic does not track properly which _task is the current one. It has many problems:
* Wait() waits for a wrong _task
* _Task is not started at all
e.g.
https://github.com/mbdavid/LiteDB/issues/2307
My repro steps were to run a lot of Inserts and Deletes in parallel (to fill up the disk queue). Then every couple of seconds run _db.Checkpoint() to force full db lock and Wait() invocation.
Fix is to use a much simpler blocking approach (one thread is dedicated to this). It is a good tradeoff IMO for now. It can be later replaced with an awaitable mutex version.
Edit: I added an async version of the semaphore which does not block the thread.

Simplified DiskWriterQueue with blocking concurrency

---

LiteDB/Engine/Disk/DiskService.cs
LiteDB/Engine/Disk/DiskWriterQueue.cs
LiteDB/Utils/AsyncManualResetEvent.cs

this includes https://github.com/mbdavid/LiteDB/pull/2411
Flush fails if the disk is full. But the internal FileStream write buffer may be still big enough to withhold some temporary issues (e.g. disk is full but OS kicks in immediately to clean up temps).
solves https://github.com/mbdavid/LiteDB/issues/2286

Disk problems

---

LiteDB/Document/BsonValue.cs
LiteDB/Engine/Disk/Serializer/BufferReader.cs
LiteDB/Engine/Disk/Serializer/BufferWriter.cs
LiteDB/Engine/Structures/CollectionIndex.cs
LiteDB/Utils/Encoding.cs

chore: throw exception when encounter unpaired surrogate instead of replace with U+FFFD

---

LiteDB/LiteDB.csproj

By using license expression it will show up correctly on nuget.org and helps license validators/checkers to know what is the exact license type.

Switch to using PackageLicenseExpression

---

LiteDB/Engine/Disk/DiskService.cs
LiteDB/Engine/Disk/Streams/AesStream.cs
LiteDB/Engine/FileReader/FileReaderV8.cs
LiteDB/Engine/Pages/BasePage.cs
LiteDB/Engine/Pages/DataPage.cs
LiteDB/Engine/Services/DataService.cs
LiteDB/Engine/Services/IndexService.cs
LiteDB/Engine/Services/TransactionService.cs
LiteDB/Utils/Constants.cs

String interpolation on hot paths leads to performance degradation. We need these messages only when error happened.
With #2453 applied this gives 3x performance boost.
This partially fixes #2451

Lazy string interpolation in ENSURE

---

LiteDB.Tests/Database/Contains_Tests.cs

Was writing tests to see if issue [#652](https://github.com/mbdavid/LiteDB/issues/652) was still an issue.
Seems to me that this is not a bug anymore.
Tested for Array, List, Enumerable assigned with an array and Enumerable assigned with a list.

Created tests that show the collections contains methods work

---

LiteDB/Engine/Disk/DiskWriterQueue.cs

This addresses #2446 
Task.Factory.StartNew tries to use task scheduler from the current task, so TaskScheduler.Default needs to be passed here.

Don't capture synchronization context in DiskWriterQueue

---

LiteDB.Tests/Mapper/Mapper_Tests.cs
LiteDB.sln
LiteDB/LiteDB.csproj
LiteDB/Mapper/BsonMapper.Deserialize.cs
LiteDB/Mapper/BsonMapper.Serialize.cs
LiteDB/Utils/Extensions/TypeInfoExtensions.cs
LiteDB/Utils/LiteException.cs

Fix the [severity issue](https://github.com/advisories/GHSA-3x49-g6rc-c284) for the old v4 liteDB version.
The goal is to have a patch for application who cannot update to V5.
Because this is my first PR for this project I think my changes should be properly checked and validated.
fix #2418 
PS: This branch should not be merged on master but probably stay on a fix branch.

Fix security issue for V4

---

LiteDB/Engine/Services/SnapShot.cs
LiteDB/Engine/Services/TransactionService.cs
LiteDB/Engine/Services/WalIndexService.cs

This PR fixes "ENSURE: empty page must be defined as empty type" error which is described in this issue: https://github.com/mbdavid/LiteDB/issues/2503

Fix "ENSURE: empty page must be defined as empty type"

---

LiteDB/Client/Mapper/BsonMapper.GetEntityMapper.cs

Fixes the final issue after #2569

Fix returning temporary mapper on concurrent access to BsonMapper
